---
title: "R Notebook"
output: html_notebook
---

```{r include=FALSE}
library(tidyverse)
library(data.table)
library(plotly)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

tuesdata <- tidytuesdayR::tt_load('2021-09-21')
tuesdata <- tidytuesdayR::tt_load(2021, week = 39)
nominees <- as.data.table(tuesdata$nominees)
```

```{r}
nominees[, `:=`(
  clean_category = tolower(gsub('.{7}$', '', category)),
  title = tolower(title),
  producer = tolower(producer),
  distributor = tolower(distributor)

)]


nom90 <- nominees %>% filter(year >= 1990)
```


```{r Best show: Double barchart}


shows <-
  nom90 %>%
  group_by(title, type) %>%
  summarise(no = n()) %>%
  spread (type, no)

shows[is.na(shows)] <- 0
shows$totalType <- shows$Nominee + shows$Winner
shows$totalTypeRatio <- shows$Winner / shows$Nominee

# Top 20 shows by:
# Winners
WStop20 <-  shows[order(-shows$Winner),][1:10,]
WStop20Sort <- WStop20[order(WStop20$totalType),]
WStop20Sort$title <- as.factor(WStop20Sort$title)



viz_dbar <- function(df, xaxis1, xaxis2, yaxis, xname1, xname2) {
  fig <- plot_ly(
    df,
    x = xaxis1,
    y = yaxis,
    type = 'bar',
    text = xaxis1,
    textposition = 'auto',
    orientation = 'h',
    name = xname1,
    marker = list(
      color = 'rgba(153, 153, 153, 0.6)',
      line = list(color = 'rgba(153, 153, 153, 1.0)', width = 3)
    )
  )
  
  fig <- fig %>% add_trace(
    x = xaxis2,
    name = xname2,
    text = xaxis2,
    textposition = 'auto',
    marker = list(
      color = 'rgba(255, 153, 0, 0.6)',
      line = list(color = 'rgba(255, 153, 0, 1.0)', width = 3)
    )
  )
  fig <- fig %>% layout(
    barmode = 'stack',
    xaxis = list(title = "Nominee and Winners"),
    yaxis = list(
      categoryorder = "array",
      categoryarray = yaxis,
      ticksuffix = " "
    )
  )
  
  
  fig
}

viz_dbar(
  WStop20Sort,
  WStop20Sort$Nominee,
  WStop20Sort$Winner,
  WStop20Sort$title,
  "Nominee",
  "Winner"
)

```

```{r Best show: Through time}







```